require "rubygems"
require "rake"

desc "Compile CSS"
task :compile do
    system "sass ../scss/basscss.scss:../basscss.css --style expanded"
    system "sass ../scss/basscss.scss:../basscss.min.css --style compressed"
    system "sass ../scss/basscss-lite.scss:../basscss-lite.css --style expanded"
    system "sass ../scss/basscss-lite.scss:../basscss-lite.min.css --style compressed"
end # task :compile

task :dev do
  system "sass . --watch"
end

